-- =============================================================================
-- Minerva V3 — WezTerm Configuration
-- =============================================================================
-- Mode-aware terminal configuration with dynamic color loading.
--
-- LUA BASICS:
-- • Lines starting with -- are comments
-- • 'local' creates a variable only accessible in this file
-- • 'require' imports a module
-- =============================================================================

local wezterm = require 'wezterm'
local config = wezterm.config_builder()

-- =============================================================================
-- MODE DETECTION
-- =============================================================================
-- Reads ~/.current-mode to determine which color scheme to load

local function get_mode()
    local home = os.getenv("HOME")
    local f = io.open(home .. "/.current-mode", "r")
    if not f then
        return "arcana"  -- Default to arcana
    end
    local mode = f:read("*all"):gsub("%s+", "")
    f:close()
    return mode
end

local mode = get_mode()

-- =============================================================================
-- LOAD MODE-SPECIFIC COLORS
-- =============================================================================
-- Colors are generated by generate-themes.sh into themes/<mode>/wezterm-colors.lua

local colors_path = os.getenv("HOME") .. "/.config/hypr/themes/" .. mode .. "/wezterm-colors.lua"

-- Try to load generated colors, fall back to defaults
local ok, colors = pcall(dofile, colors_path)
if ok and colors then
    config.colors = colors
else
    -- Fallback colors (Arcana defaults)
    config.colors = {
        foreground = '#E5E4E2',
        background = '#0E0E0E',
        cursor_bg = '#F7E7CE',
        cursor_fg = '#0E0E0E',
        cursor_border = '#F7E7CE',
        selection_bg = '#2A2A2A',
        selection_fg = '#E5E4E2',
        ansi = {
            '#0E0E0E', '#8B2F3A', '#2F6F6B', '#EED9B7',
            '#0F52BA', '#7B2CBF', '#0F52BA', '#C6C6C6',
        },
        brights = {
            '#474747', '#791B4D', '#2F6F6B', '#F7E7CE',
            '#0F52BA', '#9D4EDD', '#0F52BA', '#E5E4E2',
        },
    }
end

-- =============================================================================
-- FONT SETTINGS
-- =============================================================================

config.font = wezterm.font('JetBrains Mono', {
    weight = 'Regular',
})
config.font_size = 12.0

-- =============================================================================
-- WINDOW APPEARANCE
-- =============================================================================

-- Slight transparency (mode-aware)
if mode == "ghost" then
    config.window_background_opacity = 0.95
else
    config.window_background_opacity = 0.90
end

config.window_padding = {
    left = 12,
    right = 12,
    top = 12,
    bottom = 12,
}

-- Use Hyprland's decorations
config.window_decorations = 'RESIZE'

-- Tab bar at bottom
config.tab_bar_at_bottom = true
config.use_fancy_tab_bar = false

-- =============================================================================
-- CURSOR SETTINGS
-- =============================================================================

config.default_cursor_style = 'SteadyBar'
config.cursor_blink_rate = 500

-- =============================================================================
-- KEYBINDINGS
-- =============================================================================

local act = wezterm.action

config.keys = {
    -- Split panes
    { key = 'h', mods = 'CTRL|SHIFT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
    { key = 'v', mods = 'CTRL|SHIFT', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },

    -- Navigate panes
    { key = 'LeftArrow', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Left' },
    { key = 'RightArrow', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Right' },
    { key = 'UpArrow', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Up' },
    { key = 'DownArrow', mods = 'CTRL|SHIFT', action = act.ActivatePaneDirection 'Down' },

    -- Close pane
    { key = 'w', mods = 'CTRL|SHIFT', action = act.CloseCurrentPane { confirm = true } },

    -- New tab
    { key = 't', mods = 'CTRL|SHIFT', action = act.SpawnTab 'CurrentPaneDomain' },

    -- Font size
    { key = '+', mods = 'CTRL|SHIFT', action = act.IncreaseFontSize },
    { key = '-', mods = 'CTRL', action = act.DecreaseFontSize },
    { key = '0', mods = 'CTRL', action = act.ResetFontSize },

    -- Copy/Paste
    { key = 'c', mods = 'CTRL|SHIFT', action = act.CopyTo 'Clipboard' },
    { key = 'v', mods = 'CTRL|SHIFT', action = act.PasteFrom 'Clipboard' },

    -- Reload config (useful after mode switch)
    { key = 'r', mods = 'CTRL|SHIFT', action = act.ReloadConfiguration },
}

-- =============================================================================
-- MISC SETTINGS
-- =============================================================================

config.scrollback_lines = 10000

config.skip_close_confirmation_for_processes_named = {
    'bash', 'sh', 'zsh', 'fish', 'nu',
}

config.default_prog = { '/bin/zsh' }

config.visual_bell = {
    fade_in_duration_ms = 75,
    fade_out_duration_ms = 75,
    target = 'CursorColor',
}

-- =============================================================================
-- RETURN CONFIG
-- =============================================================================

return config
