# =============================================================================
# Minerva V3 — Hyprlock Config (Generated)
# =============================================================================
# Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
# Edit colors/colors.sh and regenerate instead.
# =============================================================================

# Mode: $MODE

background {
    monitor =
    path = screenshot
    blur_passes = ${BLUR_PASSES}
    blur_size = ${BLUR_SIZE}
    brightness = 0.7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgb(${PRIMARY_RAW})
    inner_color = rgb(${BG_SURFACE_RAW})
    font_color = rgb(${TEXT_PRIMARY_RAW})
    fade_on_empty = false
    placeholder_text = <span foreground="##${TEXT_MUTED}">Password...</span>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(${ACCENT_RAW})
    font_size = 96
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgb(${TEXT_SECONDARY_RAW})
    font_size = 20
    font_family = JetBrains Mono
    position = 0, 0
    halign = center
    valign = center
}

# Mode indicator (shows current mode)
label {
    monitor =
    text = $MODE mode
    color = rgb(${PRIMARY_RAW})
    font_size = 14
    font_family = JetBrains Mono
    position = 0, -200
    halign = center
    valign = center
}
