# =============================================================================
# Minerva V3 — Hyprland Colors Template
# =============================================================================
# Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
# Edit colors/colors.sh and regenerate instead.
# =============================================================================

# Mode: $MODE

# === HYPRLAND COLOR VARIABLES ===
$col_bg_base = rgba(${BG_BASE_RAW}${TR_FULL})
$col_bg_surface = rgba(${BG_SURFACE_RAW}${TR_FULL})
$col_bg_elevated = rgba(${BG_ELEVATED_RAW}${TR_FULL})
$col_border = rgba(${BORDER_RAW}${TR_FULL})
$col_border_inactive = rgba(${BORDER_RAW}${TR_MED})

$col_text_primary = rgba(${TEXT_PRIMARY_RAW}${TR_FULL})
$col_primary = rgba(${PRIMARY_RAW}${TR_FULL})
$col_primary_hover = rgba(${PRIMARY_HOVER_RAW}${TR_FULL})
$col_secondary = rgba(${SECONDARY_RAW}${TR_FULL})
$col_accent = rgba(${ACCENT_RAW}${TR_FULL})

$col_success = rgba(${SUCCESS_RAW}${TR_FULL})
$col_error = rgba(${ERROR_RAW}${TR_FULL})

# === DECORATION VALUES ===
$gaps_in = ${GAPS_IN}
$gaps_out = ${GAPS_OUT}
$border_size = ${BORDER_SIZE}
$rounding = ${ROUNDING}
$blur_size = ${BLUR_SIZE}
$blur_passes = ${BLUR_PASSES}
