/* =============================================================================
 * Minerva V3 — Rofi Colors (Generated)
 * =============================================================================
 * Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
 * Edit colors/colors.sh and regenerate instead.
 * ============================================================================= */

* {
    /* Mode: $MODE */

    /* Base */
    bg-base: ${BG_BASE};
    bg-surface: ${BG_SURFACE};
    bg-elevated: ${BG_ELEVATED};
    border-color: ${BORDER};

    /* Text */
    text-primary: ${TEXT_PRIMARY};
    text-secondary: ${TEXT_SECONDARY};
    text-muted: ${TEXT_MUTED};

    /* Accents */
    primary: ${PRIMARY};
    secondary: ${SECONDARY};
    accent: ${ACCENT};

    /* Semantic */
    success: ${SUCCESS};
    error: ${ERROR};

    /* Decoration */
    border-radius: ${ROUNDING}px;

    /* Apply to Rofi elements */
    background-color: transparent;
    text-color: @text-primary;
}

window {
    background-color: @bg-base;
    border: 2px solid @primary;
    border-radius: @border-radius;
    padding: 20px;
}

mainbox {
    background-color: transparent;
    spacing: 10px;
}

inputbar {
    background-color: @bg-surface;
    border-radius: @border-radius;
    padding: 12px;
    spacing: 10px;
}

prompt {
    color: @primary;
    font-weight: bold;
}

entry {
    color: @text-primary;
    placeholder-color: @text-muted;
}

listview {
    background-color: transparent;
    lines: 8;
    spacing: 4px;
}

element {
    background-color: transparent;
    padding: 10px 12px;
    border-radius: @border-radius;
}

element normal.normal {
    background-color: transparent;
    text-color: @text-secondary;
}

element selected.normal {
    background-color: @primary;
    text-color: @text-primary;
}

element alternate.normal {
    background-color: transparent;
    text-color: @text-secondary;
}

element-text {
    background-color: transparent;
    text-color: inherit;
}

element-icon {
    background-color: transparent;
    size: 24px;
}

message {
    background-color: @bg-surface;
    border-radius: @border-radius;
    padding: 10px;
}

textbox {
    background-color: transparent;
    text-color: @text-secondary;
}
