/* =============================================================================
 * Minerva V3 — swaync Stylesheet (Generated)
 * =============================================================================
 * Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
 * Edit colors/colors.sh and regenerate instead.
 * ============================================================================= */

/* Mode: $MODE */

/* === BASE === */
* {
    font-family: "JetBrains Mono", monospace;
    font-size: 13px;
}

/* === CONTROL CENTER === */
.control-center {
    background: alpha(${BG_BASE}, 0.95);
    border: 2px solid ${PRIMARY};
    border-radius: ${ROUNDING}px;
    padding: 12px;
}

.control-center-list {
    background: transparent;
}

/* === NOTIFICATIONS === */
.notification {
    background: ${BG_SURFACE};
    border: 1px solid ${BORDER};
    border-radius: ${ROUNDING}px;
    padding: 12px;
    margin: 6px 12px;
}

.notification.critical {
    border-color: ${ERROR};
}

.notification-content {
    padding: 8px;
}

.summary {
    color: ${TEXT_PRIMARY};
    font-weight: bold;
    font-size: 14px;
}

.body {
    color: ${TEXT_SECONDARY};
    font-size: 12px;
}

.time {
    color: ${TEXT_MUTED};
    font-size: 11px;
}

/* === NOTIFICATION ACTIONS === */
.notification-action {
    background: ${BG_ELEVATED};
    color: ${TEXT_PRIMARY};
    border: 1px solid ${BORDER};
    border-radius: ${ROUNDING}px;
    padding: 6px 12px;
    margin: 4px;
}

.notification-action:hover {
    background: ${PRIMARY};
    border-color: ${PRIMARY};
}

/* === CLOSE BUTTON === */
.close-button {
    background: transparent;
    color: ${TEXT_MUTED};
    border-radius: 50%;
    min-width: 24px;
    min-height: 24px;
}

.close-button:hover {
    background: ${ERROR};
    color: ${TEXT_PRIMARY};
}

/* === TOGGLE BUTTONS === */
.toggle {
    background: ${BG_ELEVATED};
    border: 1px solid ${BORDER};
    border-radius: ${ROUNDING}px;
    padding: 8px 16px;
}

.toggle:checked {
    background: ${PRIMARY};
    border-color: ${PRIMARY};
}

/* === SLIDER === */
scale trough {
    background: ${BG_ELEVATED};
    border-radius: 4px;
    min-height: 8px;
}

scale highlight {
    background: ${PRIMARY};
    border-radius: 4px;
}

scale slider {
    background: ${ACCENT};
    border-radius: 50%;
    min-width: 16px;
    min-height: 16px;
}

/* === DND === */
.dnd {
    background: ${BG_ELEVATED};
    border: 1px solid ${BORDER};
    border-radius: ${ROUNDING}px;
    padding: 8px;
}

.dnd:checked {
    background: ${ERROR};
    border-color: ${ERROR};
}

/* === WIDGET BUTTONS === */
.widget-buttons-grid {
    padding: 8px;
}

.widget-buttons-grid > button {
    background: ${BG_ELEVATED};
    border: 1px solid ${BORDER};
    border-radius: ${ROUNDING}px;
    padding: 12px;
    margin: 4px;
}

.widget-buttons-grid > button:hover {
    background: ${BG_HIGHLIGHT};
}
