/* =============================================================================
 * Minerva V3 — Waybar Stylesheet (Generated)
 * =============================================================================
 * Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
 * Edit colors/colors.sh and regenerate instead.
 * ============================================================================= */

/* Mode: $MODE */

/* === CSS VARIABLES === */
@define-color bg_base ${BG_BASE};
@define-color bg_surface ${BG_SURFACE};
@define-color bg_elevated ${BG_ELEVATED};
@define-color border ${BORDER};
@define-color text_primary ${TEXT_PRIMARY};
@define-color text_secondary ${TEXT_SECONDARY};
@define-color text_muted ${TEXT_MUTED};
@define-color primary ${PRIMARY};
@define-color secondary ${SECONDARY};
@define-color accent ${ACCENT};
@define-color success ${SUCCESS};
@define-color warning ${WARNING};
@define-color error ${ERROR};

/* === BASE STYLING === */
* {
    font-family: "JetBrains Mono", "JetBrainsMono Nerd Font", monospace;
    font-size: 13px;
    min-height: 0;
    border: none;
    border-radius: 0;
}

window#waybar {
    background-color: alpha(@bg_base, 0.9);
    color: @text_primary;
}

window#waybar.hidden {
    opacity: 0.2;
}

/* === MODULES === */
#workspaces,
#mode,
#clock,
#battery,
#cpu,
#memory,
#network,
#pulseaudio,
#tray,
#custom-power {
    padding: 0 12px;
    margin: 4px 2px;
    background-color: @bg_surface;
    border-radius: ${ROUNDING}px;
}

/* === WORKSPACES === */
#workspaces button {
    padding: 0 8px;
    color: @text_muted;
    background: transparent;
}

#workspaces button:hover {
    background: @bg_elevated;
    color: @text_primary;
}

#workspaces button.active {
    background: @primary;
    color: @text_primary;
}

#workspaces button.urgent {
    background: @error;
    color: @text_primary;
}

/* === CLOCK === */
#clock {
    font-weight: bold;
    color: @accent;
}

/* === BATTERY === */
#battery {
    color: @success;
}

#battery.charging {
    color: @success;
}

#battery.warning:not(.charging) {
    color: @warning;
}

#battery.critical:not(.charging) {
    color: @error;
    animation: blink 0.5s linear infinite alternate;
}

/* === NETWORK === */
#network {
    color: @primary;
}

#network.disconnected {
    color: @error;
}

/* === PULSEAUDIO === */
#pulseaudio {
    color: @secondary;
}

#pulseaudio.muted {
    color: @text_muted;
}

/* === CPU/MEMORY === */
#cpu, #memory {
    color: @text_secondary;
}

/* === TRAY === */
#tray {
    background-color: @bg_surface;
}

#tray > .passive {
    -gtk-icon-effect: dim;
}

#tray > .needs-attention {
    -gtk-icon-effect: highlight;
    background-color: @error;
}

/* === CUSTOM POWER === */
#custom-power {
    color: @error;
    padding: 0 16px;
}

#custom-power:hover {
    background-color: @error;
    color: @text_primary;
}

/* === ANIMATIONS === */
@keyframes blink {
    to {
        color: @text_primary;
    }
}
