-- =============================================================================
-- Minerva V3 — WezTerm Colors (Generated)
-- =============================================================================
-- Generated by generate-themes.sh — DO NOT EDIT DIRECTLY
-- Edit colors/colors.sh and regenerate instead.
-- =============================================================================

return {
    -- Mode: $MODE

    -- Background & Foreground
    foreground = '${TEXT_PRIMARY}',
    background = '${BG_BASE}',

    -- Cursor
    cursor_bg = '${ACCENT}',
    cursor_fg = '${BG_BASE}',
    cursor_border = '${ACCENT}',

    -- Selection
    selection_bg = '${BG_ELEVATED}',
    selection_fg = '${TEXT_PRIMARY}',

    -- ANSI Colors
    ansi = {
        '${BG_BASE}',      -- black
        '${ERROR}',        -- red
        '${SUCCESS}',      -- green
        '${WARNING}',      -- yellow
        '${SECONDARY}',    -- blue
        '${PRIMARY}',      -- magenta
        '${INFO}',         -- cyan
        '${TEXT_SECONDARY}', -- white
    },
    brights = {
        '${BG_ELEVATED}',  -- bright black
        '${ACCENT}',       -- bright red
        '${SUCCESS}',      -- bright green
        '${ACCENT}',       -- bright yellow
        '${SECONDARY}',    -- bright blue
        '${PRIMARY_HOVER}', -- bright magenta
        '${PRIMARY}',      -- bright cyan
        '${TEXT_PRIMARY}', -- bright white
    },

    -- Tab Bar
    tab_bar = {
        background = '${BG_SURFACE}',
        active_tab = {
            bg_color = '${BG_ELEVATED}',
            fg_color = '${TEXT_PRIMARY}',
        },
        inactive_tab = {
            bg_color = '${BG_SURFACE}',
            fg_color = '${TEXT_MUTED}',
        },
        inactive_tab_hover = {
            bg_color = '${BG_HIGHLIGHT}',
            fg_color = '${TEXT_SECONDARY}',
        },
        new_tab = {
            bg_color = '${BG_SURFACE}',
            fg_color = '${TEXT_MUTED}',
        },
        new_tab_hover = {
            bg_color = '${PRIMARY}',
            fg_color = '${TEXT_PRIMARY}',
        },
    },
}
